### ISSUE TITLE
Code Review / Empirical Roadmap Meeting To-Do

### ISSUE THREAD

**Issue by bocajnotnef** [devosoft/Empirical#88]
- [x] when do we require c++14?
- [x] what're we doing about testing? (Catch, Charles' framework, testing with clang, travis v jenkins)
- [x] What're we doing about test coverage? (Would Punch know anything?)
- [ ] How do we want to handle modules w/ non-core additions? (e.g. `jgf/new-orgs`)
- [x] Enforcing code coverage / code review before merge
- [x] Documentation! Argh!
- [x] official / enforced style guide?
- [ ] roadmap to 0.1 release?

**Comment by bocajnotnef** [comment]
Organization
-----------------

How should `evo/` be orgaized? What should be included, what shouldn't?

 - all modules should be their own repository, to limit commit/news/issue pollution to those interested in purely Empirical, not all the things that use it

 - move `evo/` to Evoke as it's own project?

note: Empirical should have autotesting of other modules for acceptance and moar coverage
Use the git tag system! (see also: python's versioneer)

**Comment by bocajnotnef** [comment]
Changelog etc.
--------------------

Point of release notes: informing the users of why they should care about moving to a new version, if anything's been deprectated/removed/changed s.t. they need to do something

Need a record of interface changes and feature additions

Changelog idea: rolling release notes style, where if you change/add something you make/modify an entry in a file in the project root

**Comment by bocajnotnef** [comment]
c++14 migration
---------------

 - aesthetically, would make things look nicer. Would not prevent/encourage features, specifically.
 - Hold for 6months

**Comment by bocajnotnef** [comment]
testing
-------

 - split up the tests into their own files, compile and run separately
 - look into `make -j` for threading
 - consider running a Jenkins server (our own g++! imagine that!)

**Comment by bocajnotnef** [comment]
Code coverage
-------------

 - if we can track coverage, put it all in catch; if not, both in catch and examples.
 - would be good to enforce code coverage--can't be worried about until we have a way to accurately

**Comment by bocajnotnef** [comment]
documentation
-------------

 - @CAO: docs on debugging tools, etc
 - @JGF: docs on 'how to be an empirical developer'
 - see https://empirical.readthedocs.io
 - style guide: 100 line breaks
 - Charles should make a readthedocs acct, s.t. I can make him a maintainer. Bus factor, etc.

**Comment by bocajnotnef** [comment]
fate of evo library
-------------------

 - what should population managers be responsible for?
 - Let's keep it integrated for now, possibly move to `applications/` when there's 2-3 more applications, when there's 10-15 applications, move everything out.

**Comment by mercere99** [comment]
Most of this is now in good shape, especially with Emily's additions allowing us to analyze code coverage.  We should still finalize a roadmap to release (we should be very close!), but I think that's the most critical todo still on here so I'm closing for now.
